### ISSUE TITLE
import proplem

### ISSUE THREAD

**Issue by EngKhaled91** [acsicuib/YAFS#1]
Thanks for your Fog Simulator but when I want to make my first Example in this url:
[https://yafs.readthedocs.io/en/latest/introduction/basic.html#network-topology](url)
 I got the following error
_import error no module named sim.topology_
any know about this problem ??
thanks

**Comment by wisaaco** [comment]
Hi,

I am currently finishing the building of several examples and I have not had time to modify the documentation with the changes of the latest version. And I still have to finish the tutorial of the documentation. 

A few minutes ago, I have updated the latest changes in the documentation. The prefix "sim" (old name) is not correct, but "yafs". Moreover, you will see more updates. 

`import yafs.topology`

You can find some examples in GitHub repository (https://github.com/acsicuib/YAFS)

Regards!
