### ISSUE TITLE
Regarding the new mobileTutorial

### ISSUE THREAD

**Issue by davidperezabreu** [acsicuib/YAFS#12]
I am trying to execute the mobile tutorial example provided in one of the last updates of the project without success. My issue is related to the import of the osmnx package, which requires networkx v2.3; however, this version is just available on the pip branches for Python 3. I was wondering if you are using different environments for the examples provided or if I am missing something else? Could you enlighten me on this issue?

Best regards,

**Comment by wisaaco** [comment]
Hello David,

These are my library versions on Python 2.7.14:
osmnx==0.8.2
networkx==2.2

You can try to install a specific python library with the following command (in case you have both python versions 2.7 and 3.x):
$ sudo python2.7 -m pip install osmnx==0.8.2

Best

**Comment by davidperezabreu** [comment]
Hi Issac,

Thanks for your reply. Effectively, my issues were related to the versions of the packages that I installed, as you know, pip tries to install the last version of the package which is 1.0 for osmnx and that one requires Python 3. I installed osmnx==0.9 and I was able to run the mobility Tutorial. Additionally, I had to install in my system (Ubuntu 18.04) these extra packages via apt: libspatialindex-c4v5 and ffmpeg

I took the liberty to create a conda environment with all the necessary packages that are necessary to run YAFS’ experiments, which is available in this link (yafs.yml): [https://github.com/davidperezabreu/toshare]. This dependencies’ file could pave the way for people that want to use the simulator without too much effort.

Cheers,

David.

**Comment by wisaaco** [comment]
Awesome! Thanks a lot David!! _Obrigado_!

I would like to have more extra time to finish the "non-important" TODO tasks of the simulator. I thank you very much for doing this task and with your permission, I would like to include your link in the Readme document.
I have yet to implement more communication policies between mobile entities and implement more cases.
If you need help to develop a custom policy or to analyze the results of the simulator, do not hesitate to tell me.

Best,
Isaac
