### ISSUE TITLE
about API document

### ISSUE THREAD

**Issue by jiaweiwangwang** [acsicuib/YAFS#18]
I want to use the YAFS simulator in my experiment, but I can't find the related API on your recommended website.(https://yafs.readthedocs.io/en/latest/api_reference/index.html).Please tell me how can I find the specific  API document?

**Comment by wisaaco** [comment]
Hello,

Yeah, you are right. There is a problem with the automatic doc generator. I will try to fix this problem in these days.

Meanwhile, with some basic tutorials (in folder examples) and with this section (https://yafs.readthedocs.io/en/latest/introduction/basic.html), you can get an idea of the possibilities of the simulator. The most important aspect is the implementation of your policies.

Thanks!
