### ISSUE TITLE
About FogCentrality\Experiment1.py

### ISSUE THREAD

**Issue by MatiasNMont** [acsicuib/YAFS#19]
Hi! I need to test the latency in different topologies. In the documentation you talk of FogCentrality\Experiment1.py that this script measures the latency, but I cant find this scripts

"FogCentrality/experiment1.py In this case, we have analysed how the topology and the allocation of modules affects in the latency time."

Regards

**Comment by wisaaco** [comment]
Hello Matias,

The file was ignored in the github configuration... sorry
It's already updated!

https://github.com/acsicuib/YAFS/tree/master/src/examples/FogCentrality

Best,
Isaac
