### ISSUE TITLE
A couple of naming issues

### ISSUE THREAD

**Issue by jonlwowski012** [acsicuib/YAFS#2]
There were are couple of naming issue that caused install to fail and for importing yafs to fail.

**Comment by wisaaco** [comment]
Thanks, Jonathan.

**Comment by jonlwowski012** [comment]
When will you merge my changes?

**Comment by jonlwowski012** [comment]
Also when will this get patched in python pip

**Comment by wisaaco** [comment]
I will try to do next week. And also, I should update the python pip.
Thanks, and sorry for close the issue.
