### ISSUE TITLE
Customized termination of simulation

### ISSUE THREAD

**Issue by Ktechkun** [acsicuib/YAFS#25]
How to terminate simulation using any custom measure other than time. For example if i wanted to stop simulation after N number of app successfully terminated.

**Comment by wisaaco** [comment]
In class Core.py, you can set the boolean variable stop at True.
sim.stop = True
All internal simulator processes will stop when they are activated again.

**Comment by Ktechkun** [comment]
So, like in file like SimpleSelection i can set sim.stop = 0. Thanks
