### ISSUE TITLE
Regarding mobility simulation

### ISSUE THREAD

**Issue by kannonical** [acsicuib/YAFS#26]
Can the mobile nodes (users) in the simulation be used to deploy services?

**Comment by wisaaco** [comment]
Yes. A node can host users and services at the same time.

**Comment by kannonical** [comment]
Thank you so much. I have another question regarding the 'node utilization' measure, mentioned in the IEEE access paper. But I could not find the means to measure it. 
Also I found a slide set related to YAFS which was very useful. But I cannot find it now. Could you let me know a link for it?

**Comment by wisaaco** [comment]
You can compute the utilization of a node using the csv file. (https://yafs.readthedocs.io/en/latest/introduction/basic.html#results) It can be performed during the simulation or at the end. 
There are different ways. Perhaps, the most simple one is considering the accumulated busy time of a specific node (_topo.src_ csv-column) so: utilization_node = sum_busy_times_node/  simulation_time. You can use the Pandas library to perform the analysis.

**Comment by kannonical** [comment]
Thank you for your help. I defined two applications in appDefinition.json but get the following result. What is unusual is it registers a single message information (M.USER.APP.2) and has a fixed service time for all id. Could you suggest what I am doing wrong? 
![Screenshot from 2019-11-19 17-16-21](https://user-images.githubusercontent.com/10186011/69169713-bbf44c80-0af0-11ea-91ed-12aa888da599.png)

**Comment by kannonical** [comment]
There was an issue in my app definition and I could resolve it. 
However I still have a doubt about being able to record the entries for only source messages? 
Is there a way to trace intermediate messages?

**Comment by wisaaco** [comment]
In this file, all the messages that are attended by a service are registered. If your app have multiples services, each "service" generates one log line.  How many services do you have in each app?
On the other hand, in the csv file (x**_link**.csv),  the communication messages are recorded.

**Comment by kannonical** [comment]
Hi, thanks again. I apologize for bothering you with the trivialities. 
Please find attached my appDefinition.json
                                                                                                                                                                                                     appDefinition.json                                                                                                                                                                                                                          

[
  {
    "name": "2",
    "transmission": [
      {
        "module": "2_19",
        "message_in": "M.USER.APP.2"
      },
      {
        "message_out": "M.USER.APP.4",
        "message_in": "M.USER.APP.2",
        "module": "2_19",
        "fractional" : "1"
      },
      {
        "message_out": "M.USER.APP.5",
        "message_in": "M.USER.APP.4",
        "module": "2_20",
        "fractional": "1"
      },
      {
        "module":"2_21",
        "message_in":"M.USER.APP.5"
      }
    ],
    "module": [
      {
        "RAM": 30,
        "type": "MODULE",
        "id": 19,
        "name": "2_19"
      },
      {
        "RAM": 10,
        "type": "MODULE",
        "id":22,
        "name": "2_20"
      },
      {
        "RAM": 10,
        "type": "MODULE",
        "id":23,
        "name": "2_21"
      }
    ],
    "deadline": 48723.22,
    "message": [
      {
        "d": "2_19",
        "bytes": 26222,
        "name": "M.USER.APP.2",
        "s": "None",
        "id": 0,
        "instructions": 33753
      },
      {
        "d": "2_19",
        "bytes": 2621222,
        "name": "M.USER.APP.4",
        "s": "2_20",
        "id": 1,
        "instructions": 33753
      },
      {
        "d": "2_20",
        "bytes": 264522111,
        "name": "M.USER.APP.5",
        "s": "2_21",
        "id": 2,
        "instructions": 33753
      }
    ],
    "id": 2
  },
  {
    "name": "3",
    "transmission": [
      {
        "module": "2_22",
        "message_in": "M.USER.APP.3"
      }
    ],
    "module": [
      {
        "RAM": 3,
        "type": "MODULE",
        "id": 22,
        "name": "2_22"
      }
    ],
    "deadline": 474.51,
    "message": [
      {
        "d": "2_22",
        "bytes": 275,
        "name": "M.USER.APP.3",
        "s": "None",
        "id": 0,
        "instructions": 445
      }
    ],
    "id": 3
  }
]

**Comment by wisaaco** [comment]
No worries.
In your appDefinition.json, I recommend you keep unique the names of the entities. For example, you have the next code:
````
{
"name": "3",
"transmission": [
{
"module": "2_22",
"message_in": "M.USER.APP.3"
}
],
"module": [
{
"RAM": 3,
"type": "MODULE",
"id": 22,
"name": "2_22"
}
],
````

The right thing is:
````
{
"name": "3",
"transmission": [
{
"module": "3_22",
"message_in": "M.USER.APP.3"
}
],
"module": [
{
"RAM": 3,
"type": "MODULE",
"id": 22,
"name": "3_22"
}
],
````
And it's better to define different name messages for each app. It means, the applications do not share messages between them. 

How is your "allocDefinition.json"? Do all the services (json "modules") have a placement?
