### ISSUE TITLE
load balancing

### ISSUE THREAD

**Issue by Ktechkun** [acsicuib/YAFS#28]
How can I get current load on each node, also deploy according to available resources at a given time?

**Comment by Ktechkun** [comment]
Can i get execution start time and end time of a task/module of specific application identified by id.
How can i decide node is capable to execute task, when the message reaches the destination node, do i need to implement a dict to store execution load at different times?

**Comment by sanket099** [comment]
@Ktechkun Were you able to find the answers to those questions? Please share the solutions to them , if you did

**Comment by wisaaco** [comment]
One of both CSV files stores all tasks/messages executions. You can use pandas or another library to analyse the file (along with the execution or at the end). You can use the ID of the process (DES) to analyse the utilization or the ID of the node.  Please take a look at the slides to understand the data of both files.
