### ISSUE TITLE
Which IDE is suitable for YAFS

### ISSUE THREAD

**Issue by maqsood-tahir** [acsicuib/YAFS#32]
Hi,

Can anyone guide me that which IDE is suitable or more compatible with YAFS? 
If someone has done integration with any IDE, please share their experience. 

Thanks

**Comment by wisaaco** [comment]
I use PyCharm. It manages the working paths, the python environments, code autocomplete, git integration, and so on.  PyCharm has a free version (https://www.jetbrains.com/pycharm/)

**Comment by maqsood-tahir** [comment]
Many thanks for the advice. Successfully integrated and executed the code in PyCharm. 
Thanks again :)
