### ISSUE TITLE
m.load_results in FogCenrality  not found

### ISSUE THREAD

**Issue by roshangol** [acsicuib/YAFS#39]
I try to run analyse_resulte.py in example/FogCenrality but metrics module not have load_results. Please help me to run this code. Thanks

**Comment by wisaaco** [comment]
Hello, 
You can use Pandas to load the models.  
Change this code:
```python
            m.load_results("results_exp/results_exp_%s_%i_%s" % (topo,size,f))
            df,dl = m.get()
```
and use this:
```python
            dl = pd.read_csv("results_exp/results_exp_%s_%i_%s_link.csv" % (topo,size,f))
```
Note: Please, take care of the file name in results_exp folder.

**Comment by roshangol** [comment]
@wisaaco thanks. Your answer solve my problem.
