### ISSUE TITLE
About time unit

### ISSUE THREAD

**Issue by wei12f8158** [acsicuib/YAFS#40]
hi~
In this paper mention the "400 time" units.

https://ieeexplore.ieee.org/document/8758823
![螢幕擷取畫面 2021-03-17 155216](https://user-images.githubusercontent.com/49111480/111433517-57272180-8739-11eb-8a5e-dae42558bcab.png)

I am confuse what the actually time units mean?  ex: 400 MilliSeconds or MicroSeconds etc.

thx :)

**Comment by wisaaco** [comment]
Hello,
YAFS is a discrete event simulator. Thus, the events are equals for all the "events": rate of requests, time service, time response, etc.  If you decide that the movements happen every 400 seconds or 400 ms, the other values have the same unit, in this paragraph, the request rate. So, 400s implies 100s or 400 years implies 100 years. Basically, you choose the time unit.
Best
