### ISSUE TITLE
Get node resource usage during simulation

### ISSUE THREAD

**Issue by andremtsilva** [acsicuib/YAFS#44]
Hi @wisaaco, 

Is there any way I can get information about the capacity usage of the nodes throughout the simulation? For example, a node with 100 IPT of capacity that is receiving two messages of 30 instructions every 100 units of time. I can get this 40 IPT residual to decide if I can send another message.

**Comment by wisaaco** [comment]
Hello @andremtsilva ,
From my point of view, one way to get a similar indicator of capacity usage is to obtain the ratio between the receiving requests from a specific period and the total number of requests that the service can serve. The total number of requests can be a constant from your application. 

So, you could split into several periods: T1-T2-T3...Tn your simulation. At the end of each period, you can control the total number of arrival requests. It is a weird trick but it is a common problem of DES simulators.

To obtain the requests you can do the following. First, you need to create a custom process that runs each period. In this custom process, you obtain the number of requests of each deployed service/app -if you wish you can filter the services, of course-. 

You can do/adapt the following code, where the self.DES is the ID of each service/app (bottom part)

In this code, the goal is to obtain several sentences of this style of one self.DES: 
```
requests(self.DES, last neighbour node where requests are generated, number of arrival requests, latency)
```

For example, it coud generate this:
requests(1, n10, 5, 20)
requests(1, n9, 10, 30)

with the following topology:  
n1--n10--nY-userX
   \--n9--nX-userY

where service ID:1 is deployed on n1
and both users requests service from ID:1 on n1
The sum of 5 plus 10 gives you an idea of the utilization rate.


```python
           ################################################################################
            # REQUEST fact
            # requests(ServiceInstanceId, Neighbour, RequestRate, LatencyToClient).
            ################################################################################
            # The request rate is the number of  messages in the path's request
            # To obtain the the number of msg get need to analyse the simulation results on the csv file
            sim.metrics.flush()
            # We only load samples that are generated along current period (self.activations-1,self.activation)
            df = pd.read_csv(self.path_csv_files + ".csv", skiprows=range(1,self.load_samples_from))  # It includes the csv header
            self.load_samples_from += len(df.index)   # avoid header

            # print("AGENT LOADING REQUESTS")
            # print("SERVICE DES:",self.DES)
            # print("TIME:",sim.env.now)
            # print("OFFSET: ",self.load_samples_from)
            # print("DF len : ",len(df))
            # print("REQUEST ",requests)

            df = df[df["DES.dst"] == self.DES]

            # print("DF2 len : ", len(df))

            if len(df) > 0:
                #WARNING . If the topology changes (ie. node failure) this code should be checked again
                dg = df.groupby("TOPO.src")["TOPO.src"].count()
                for node_src, sumMessages in dg.iteritems():
                    path = routing.get_path_from_src_dst(sim,node_src,currentNode)

                    latency = self.get_latency(path,sim.topology)
                    if sumMessages > 0:
                        if len(path)==1:
                            # node_code= ["self"]
                            node_name = ["self"]
                        else:
                            node_code = path[-2]
                            if (self.reversepath + 1) > len(path)-1:
                                node_code = path[0:-1]
                            else:
                                node_code = path[-(self.reversepath+1):-1]
                            node_name = ["n%i"%x for x in node_code]
                        self.rules.and_rule("requests", "s%i"%self.DES, node_name, sumMessages, latency)
            else:
                # print("INFO - No messages among users and service")
                self.logger.warning("WARN - There are not new messages among users and service")
```
code from: https://github.com/acsicuib/MARIO/blob/SI-SoSs/multi-agent-policies/environment/agent.py
https://github.com/acsicuib/MARIO/tree/MarioII

**Comment by andremtsilva** [comment]
Hello @wisaaco 

I'm following your guidance on this issue and I already have a customized process (my Custom Strategy class) that is invoked every 200 units of time from start time 100.

I still have a very simple scenario with just one application and 5 users. In this scenario, the request metric looks like this:
TOPO.src	(300 ut)	500	700	900	1100	
15    		2		4	6	8	10
16    		2		4	6	8	10
17    		2		4	6	8	10
18    		2		4	6	8	10
19    		2		4	6	8	10

All of these requests are directed to the cloud node (0) at the beginning.

In this Custom Strategy class I also allocate a new application on a Fog node based on a decision heuristic.
(Like this sample from my sim_trace.csv)


id|	DES.src|	DES.dst|	TOPO.src|	TOPO.dst|	time_emit
24|	3|	9|	18|	2|	500.0
25|	4|	6|	19|	0|	500.0
26|	0|	6|	15|	0|	600.0
29|	3|	9|	18|	2|	600.0
27|	1|	6|	16|	0|	600.0
28|	2|	6|	17|	0|	600.0
30|	4|	6|	19|	0|	600.0
31|	0|	6|	15|	0|	700.0
32|	1|	10|	16|	3|	700.0



What I am not able to relate is the number of DES.dst with the node where the application was allocated to extract from that node how many requests it served.

Specifically, this relationship in a dynamic way:
 df = df[df["DES.dst"] == self.DES]

Thanks in advance for any kind of help.

@andremtsilva

**Comment by wisaaco** [comment]
Hello @andremtsilva 
From the sim_trace.csv I can figure that you have several services deployed in nodes 0, 2, and 3.  Topo.dst is the column that contains the service. So, in node 0 you have a service DES-6, in node 2 the service DES-9; and in node 3 the service DES-10. 

To obtain the number of requests that a node served (and if you have a cardinality of 1:1 with the service deployed on a node) you can do a _groupby_. 

df.groupby(['TOPO.dst']).agg(['mean', 'count'])

**Comment by andremtsilva** [comment]
Hi @wisaaco 

I ended up with a solution like this:

```
def node_request():                
            sim.metrics.flush() # metrics during Custom call
            df = pd.read_csv('results_steiner_tree3b/sim_trace.csv')                        
            dr = df.groupby("TOPO.dst")["TOPO.dst"].count()
            
            nodes = list(dr.keys())
            nodes = nodes[1:]
                    
            cap_req_const = 20 #  constant requests capacity (ex. 20)
            used_nodes = range(1, len(dr)) # 1 remove cloud node
            usage = []
            for i in used_nodes:
                node_usage = (dr.iloc[i]/cap_req_const)*100
                usage.append(node_usage)
            du = pd.DataFrame({'Nodes': nodes, 'Usage': usage})
            #print(du)
                
node_request()
```

As you said before, it's kind of a trick, but it turns out that it works as a usage metric.

I was wondering if it wouldn't be possible to obtain a usage metric by the node's IPT (instructions per time) attribute in relation to the "instructions" measure of the messages.

```
 "message": [      {        "id": 0,        "name": "M.USER.APP.1",        "s": "None",        "d": "1_01",        "bytes": 1,        **"instructions"**: 100
```
```
# IPT
    attIPT = {x: random.randrange(100, 900, 100) for x in t.G.nodes()}
    nx.set_node_attributes(t.G, name="IPT", values=attIPT)`
```

Thanks once again!
