### ISSUE TITLE
Lack of module

### ISSUE THREAD

**Issue by slomo28** [acsicuib/YAFS#45]
This is my first time to use YAFS, and I want to try the examples given, but there is a lack of coverage and customMovement module.Could you help me solve it? Thank you very much!

**Comment by wisaaco** [comment]
Hi @slomo28,
This part is not enough documented. Sorry. Basically, they are specific processes on the simulator that manage events regarding the connections (the coverage)  and the movement of entities.  It is a "communication puzzle" between the main file and these processes. Best
