### ISSUE TITLE
Output the data of the latest  tutorial_scenarios

### ISSUE THREAD

**Issue by subwayi** [acsicuib/YAFS#46]
Hi @wisaaco ,

I can successfully process the tutorial_scenarios which is the latest version.
I would like to output the data within .csv file. (there is no data in .cvs file now)
Could I change ONLY the parameter in .json file? ( allocDefinition.json / appDefinition.json / usersDefinition.json )
Or anything else can I do?  
Can you give me some advice for this?

Thank you.

**Comment by wisaaco** [comment]
If the simulation finishes right, you should get the network and computation traces in two CSV files. Please check that the simulation finishes right.
The jsons allow you to modify the topology, the initial deployment of applications and users, but you can also do it by code. If you need more complex modelling then the json are not enough.
Best

**Comment by subwayi** [comment]
Hi @wisaaco ,

Thanks for the your detailed and clear information.
Since there are four CSV files in the folder, I thought that I might miss something before.
There are data within those two traces CSV files, the simulation was finished pretty good.
The json format could present the parameter in good order, I like that.

Thank you!
