### ISSUE TITLE
Need for help 

### ISSUE THREAD

**Issue by souad46** [acsicuib/YAFS#48]
hi 
i want to use YAFS  simulator in my graduation projet , i can't install the simulato on my laptop even though I followed the documentation, could  you help me please ??
  best regards

**Comment by wisaaco** [comment]
Of course, Could you provide more details on the steps you have followed and on what system and version of python?

**Comment by souad46** [comment]
good evening 

i followed your guide on github , i have windows 8.1 , i worked with python 3.6 , anaconda 3 and when i tried to execute the main code  of tutorial_scenarios folder i got a lot of bugs ( ModuleNotFoundError: No module named 'networkx' , etc ....) 

could you give me all the steps to install the simulator please??


 also i want to create network and store data in  blockchain , is it possible with yafs simulator ??

best regards

**Comment by wisaaco** [comment]
Hi,
You have to install the dependencies, as the guide commented: 

https://github.com/acsicuib/YAFS#installation-updated

"
Create one python virtual environment and install dependencies
   (venv)$ python -m pip install -r requirements.txt
"
You can do it, but you need to understand some Python libraries such as Numpy, Pandas and Networkx. 
Best,

**Comment by souad46** [comment]
Got it ..... thnx a lot

Le ven. 2 juil. 2021 à 07:59, Isaac.Lera ***@***.***> a
écrit :
