### ISSUE TITLE
Not able to run Tutorial/main1.py

### ISSUE THREAD

**Issue by apoorvpandey0** [acsicuib/YAFS#49]
I have installed this library using 
```pip install yafs```
Now I'm trying to run this in Tutorial folder in this repo:

```python3 main1.py```

This is what I'm getting:

```
Traceback (most recent call last):
  File "main1.py", line 15, in <module>
    from yafs.core import Sim
  File "/home/kiteuser/.local/lib/python3.6/site-packages/yafs/__init__.py", line 11, in <module>
    from yafs.core import Sim
  File "/home/kiteuser/.local/lib/python3.6/site-packages/yafs/core.py", line 1007
    print "-"*40
            ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("-"*40)?

```
Did I miss something here?

**Comment by wisaaco** [comment]
Hi,

The best way -the only way- to install YAFS is using the command: git clone. Clone the last branch of the project and install the third-party library from requirements.txt file. 

Best

**Comment by apoorvpandey0** [comment]
> Hi,
> 
> The best way -the only way- to install YAFS is using the command: git clone. Clone the last branch of the project and install the third-party library from requirements.txt file.
> 
> Best

Hi, I have cloned this and kept it in a folder, but my python would not know about this cloned library right.
How to get around this? do I need to add its path somewhere etc?
