### ISSUE TITLE
API Reference 

### ISSUE THREAD

**Issue by MrrMayhem** [acsicuib/YAFS#5]
Hello,

I find your Fog Simulator very useful, and i m trying to work with on my Master Degree Project, i have read all your article and your web site but unfortunately there is still some ambiguity, so  i would like to get more information if it's possible to improve my understanding on the way it works, i will really appreciate if you could help me like giving me the API reference that you mentioned on your article. Thank you

**Comment by wisaaco** [comment]
Hi,

Thanks for your kindness,
The API is not 100% updated but you can get an idea of the main components:
The API URL: https://yafs.readthedocs.io/en/latest/
Let me recommend that you look at the examples folder, especially the tutorials.
I am at your disposal for any clarifications or extended information you may deem appropriate.

Best

**Comment by MrrMayhem** [comment]
Thank you for your response, 

In fact, i have already read your articles and take a very deep look on the tutorials, i don't understand quite well the idea of source and sink regarding the topology, in the example that i tried to build, i tried to add more sensors (sources) and actuators (sinks) to the topologie:

![1](https://user-images.githubusercontent.com/47793741/53080465-0b253680-34f9-11e9-8a0c-4d70fa99075f.png)

i noticed that the sensors send the messages to the process module but the results message are send back to the same actuator with the same path and not the other actuators:

![2](https://user-images.githubusercontent.com/47793741/53080494-1bd5ac80-34f9-11e9-936b-dd548a816667.png)

I must say that i m not an expert on computer science and Cloud/Fog environnement, so a clear and simple explanation would be very much appreciate it. Thank you !

**Comment by wisaaco** [comment]
Hello,

"Source"  is an entry point (linked to a node) where the application requests are generated. In the "fog-literature", they are called gateways, but I prefer to use the term "source" since it is similar to the used in Queueing theory. A node can have several sources from the same application o from others.
An application module can also generate application requests. For that point, there is a small difference between "pure" source or not.

"Sinks" are a special type of application nodes that they do not send a message. They have input but not an output message. 

Regarding the second issue, the routing of messages depends on the application modules. 
In that case, the response is returned to the same node/client/gateway. You have to define a path function, that it finds a path between nodes. It can be customised since you can consider several features of the network (minimum path, best latency path, etc.)

I attach you a more complex example of an application using json syntax, May be it can you give more ideas about the possible types of applications.

[
  {
    "name": "14",  <---- NAME of the app
    "transmission": [ <--- EDGES or links between modules with the type of message involved
      {
        "message_out": "14_(76-80)",
        "module": "14_76",
        "message_in": "M.USER.APP.14" .   <---- THIS IS a special "message" that is generated in a SOURCE node
      },
      {
        "message_out": "14_(76-77)",
        "module": "14_76",
        "message_in": "M.USER.APP.14"
      },
      {
        "message_out": "14_(76-78)",
        "module": "14_76",
        "message_in": "M.USER.APP.14" 
      },
      {
        "message_out": "14_(76-79)",
        "module": "14_76",
        "message_in": "M.USER.APP.14" <- So, when this message arrive to the module, the module will  generate  four types of messages (message_out)
      },
      {
        "module": "14_80",  <----- THIS MODULE IS CONSIDERED LIKE a SINK
        "message_in": "14_(76-80)"
      },
      {
        "module": "14_77",  <----- THIS MODULE IS CONSIDERED LIKE a SINK
        "message_in": "14_(76-77)"
      },
      {
        "module": "14_78", 
        "message_in": "14_(76-78)"
      },
      {
        "module": "14_79",
        "message_in": "14_(76-79)"
      }
    ],
    "module": [ <----- MODULES or part of the application, they have to deploy in the nodes
      {
        "RAM": 6,
        "type": "MODULE",
        "id": 80,
        "name": "14_80"
      },
      {
        "RAM": 2,
        "type": "MODULE",
        "id": 76,
        "name": "14_76"
      },
      {
        "RAM": 1,
        "type": "MODULE",
        "id": 77,
        "name": "14_77"
      },
      {
        "RAM": 4,
        "type": "MODULE",
        "id": 78,
        "name": "14_78"
      },
      {
        "RAM": 3,
        "type": "MODULE",
        "id": 79,
        "name": "14_79"
      }
    ],
    "deadline": 915.16,
    "message": [ .  <----- DESCRIPTION OF THE MESSAGEs
      {
        "d": "14_76",
        "bytes": 4387958,
        "name": "M.USER.APP.14",
        "s": "None",
        "id": 0,
        "instructions": 34261
      },
      {
        "d": "14_80",
        "bytes": 2729373,
        "name": "14_(76-80)",
        "s": "14_76",
        "id": 1,
        "instructions": 53767
      },
      {
        "d": "14_77",
        "bytes": 4143758,
        "name": "14_(76-77)",
        "s": "14_76",
        "id": 2,
        "instructions": 25533
      },
      {
        "d": "14_78",
        "bytes": 4276621,
        "name": "14_(76-78)",
        "s": "14_76",
        "id": 3,
        "instructions": 52143
      },
      {
        "d": "14_79",
        "bytes": 2201992,
        "name": "14_(76-79)",
        "s": "14_76",
        "id": 4,
        "instructions": 36023
      }
    ],
    "id": 14 <---AN UNIQUE IDENTIFIER
  }
]


Best

**Comment by MrrMayhem** [comment]
Hello, 

Thank you very much for your answer it was really helpful, if you don't mind i have another question, i m getting a weird message while simulating : 

![1](https://user-images.githubusercontent.com/47793741/53563824-815b1600-3b55-11e9-98fa-636dfcd828bb.png)

Can you explain to me what does it mean and why its happening.

Best regards

**Comment by wisaaco** [comment]
Hello,

In this case, we remove a node to simulate, for example, a network failure. Thus, all processes deployed in that node have to be removed as well. In this case, there is only one with identifier DES: 6

Best!

**Comment by Dhaval-Shekhada** [comment]
Hi I am working as researcher at fraunhofer.  I would like to test your framework to describe scenario with for efficient mudule allocation in node failure case with mobility.  would you please explain me about PartitionILPplacement example?  what strategy you have mentioned for placement? is it Integer Linear programming ? or something else ? I want to test it for small simulation time. where can i make changes?  would you please help me here? 

Kind regards.
Dhaval

**Comment by wisaaco** [comment]
Dear Dhaval,
"PartitionILPplacement" project implements the study carried on this paper (https://ieeexplore.ieee.org/document/8588297). There you can find more specific information about the strategy, and other important configuration parameters.
The "main.py" file implements the experiment with node failure strategy. In this implementation, this failure strategy is implemented through a function: "failureControl(sim,filelog,ids)". The network, apps, and so on are implemented with json files. 
Take a look at the tutorials to understand the basic parts of the simulator. 

Best regards
Isaac

**Comment by Dhaval-Shekhada** [comment]
Thank you for your reply. Its really helpful. :)
