### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by Sherlocked556** [acsicuib/YAFS#50]
I have been reading YAFS code for some time and I am working on reducing latency.
Like IfogSim, Is there a scheduler alogrithm available?
Also Is there any way my application module can handle different messages and process them according to fcfs or priority, considering a topology similar to main1.py in tutorial examples?

**Comment by ndganesan** [comment]
if you came across please share with us

**Comment by wisaaco** [comment]
A module can handle different requests. You define that in the app json. For example, in the next case, module 1_01 deals with two kinds of requests.

```json
"transmission": [
      {
        "message_in": "M.USER.APP.1",
        "module": "1_01",
         "message_out": "M.USER.APP.1_3",
      },
      {
        "message_in": "M.USER.APP.9",
        "module": "1_01"
      },
        {
        "message_in": "M.USER.APP.1_3",
        "module": "1_02"
      },
```

Regarding the priority, please check the related issue: #51
