### ISSUE TITLE
Python 2.7 end-of-life No IDE supporting

### ISSUE THREAD

**Issue by ndganesan** [acsicuib/YAFS#53]
I'm trying to configure YAFS in pycharm it not allowing me to add Python 2.7 as an interpreter because of end-of-life.

**Comment by wisaaco** [comment]
Hi, 
The last branch and the main of YAFS is based on Python 3.6. Take a look:
https://github.com/acsicuib/YAFS/tree/YAFS3

Best,
Isaac

**Comment by ndganesan** [comment]
Thanks for your quick reply Sir, Request you to upgrade to the latest version of python because 3.6 is also reaching the end of life by 2021-12-23.
