### ISSUE TITLE
Calculating Throughput

### ISSUE THREAD

**Issue by sanket099** [acsicuib/YAFS#54]
Throughput is a measure of how many units of information a system can process in a given amount of time. Is there a way to calculate throughput in YAFS?

**Comment by wisaaco** [comment]
Of course, you can compute the number of requests in a certain period through the CSV files according to a specific service or node. You do that computation using Pandas (or other data analytic library) using the CSV files.  Take a lookout at the slides to understand the results of a simulation.
For example, in this project and in this specific script (https://github.com/acsicuib/MARIO/blob/SI-SoSs/multi-agent-policies/environment/agent.py lines **191**:...) we get the request ratio of a specific deployed service in a dynamic way.
