### ISSUE TITLE
Mobile Tutorial missing package or simulating edge movements

### ISSUE THREAD

**Issue by vyk1** [acsicuib/YAFS#57]
I am trying to use the example in `src/examples/mobileTutorial` but the module `yafs.customMovement` does not exist.

If not possible, is there any other way I can use the simulator in the context of movimentation using the dataset provided (`ibiza.csv`)?

**Comment by wisaaco** [comment]
Hello @vyk1 ,

You can find this example (and code) in the _master_ branch. The last branch only contains the _essentials_ parts. 
Define the path of the library and your own scripts and you will not have problems with the execution of the project.

````
export PYTHONPATH="/home/X/projects/YAFS/... :/home/X/projects/YAFS/example....:$PYTHONPATH"

````

Best

**Comment by vyk1** [comment]
Hi @wisaaco, thank you for the quick reply. 
I see; I'll try using the conda environment recommended. 

As I am not familiar with Python, I would like to ask if the Python version will not be a problem when configuring the Conda environment.

Thanks again!

**Comment by vyk1** [comment]
Hello again, 
I configured the conda environment and now I ran into this problem when creating the dependency installation file: 
![image](https://user-images.githubusercontent.com/47799125/152218572-042efe8b-9961-41ee-ac86-3d2ffd93a765.png)

I tried installing v2.4.1.1 but no solution.

Any help?

**Comment by wisaaco** [comment]
The best way to work with Python from my perspective is to have multiple versions and virtual environments. In this link is explained how to proceed [url]( https://www.freecodecamp.org/news/manage-multiple-python-versions-and-virtual-environments-venv-pyenv-pyvenv-a29fb00c296f/#:~:text=If%20you%20wish%20to%20use,and%20must%20be%20installed%20separately)

Instead to use conda, maybe you can use pip. With python2 and your virtual environment installed, you can clone that branch.

**Comment by vyk1** [comment]
Cool, thanks again. 
I will try cleaning the project, too.
