### ISSUE TITLE
NoSectionError: No section: 'formatters'

### ISSUE THREAD

**Issue by Hallicopter** [acsicuib/YAFS#6]
When I run 
`python src/examples/Tutorial/main1.py`
I get
```
Traceback (most recent call last):
  File "src/examples/Tutorial/main1.py", line 152, in <module>
    logging.config.fileConfig(os.getcwd()+'/logging.ini', disable_existing_loggers=False)
  File "/usr/lib/python2.7/logging/config.py", line 77, in fileConfig
    formatters = _create_formatters(cp)
  File "/usr/lib/python2.7/logging/config.py", line 113, in _create_formatters
    flist = cp.get("formatters", "keys")
  File "/usr/lib/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
NoSectionError: No section: 'formatters'
```

**Comment by wisaaco** [comment]
Change the path of logging.ini file in the following line according to your execution path.
For example, you can use the os library:
import os  
logging.config.fileConfig(os.getcwd() + '/logging.ini')

**Comment by saad-eddine** [comment]
Hi 
I have the same problem , 
When I run
python src/examples/Tutorial/main1.py 
```
Traceback (most recent call last):
  File "src/examples/Tutorial/main1.py", line 155, in <module>
    logging.config.fileConfig(os.getcwd()+'/logging.ini')
  File "/usr/lib/python2.7/logging/config.py", line 77, in fileConfig
    formatters = _create_formatters(cp)
  File "/usr/lib/python2.7/logging/config.py", line 113, in _create_formatters
    flist = cp.get("formatters", "keys")
  File "/usr/lib/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
NoSectionError: No section: 'formatters'

```

**Comment by wisaaco** [comment]
Hello,
Your python working directory is wrong with the running directory.  

The easy solution is to comment the lines regarding the logging functions.

In main.py file, you can comment the last 3 lines:
```
if __name__ == '__main__':

    import logging.config
    import os
    logging.config.fileConfig(os.getcwd()+'/logging.ini')

```

**Comment by saad-eddine** [comment]
Hi using your simulator , i can get the energy consumption of the node

**Comment by wisaaco** [comment]
Hello,
You can obtain the utilization of a specific resource and other performance basic measures that it can be used to compute the energy consumption, but the energy consumption model has to be implemented, it is your specific model. You can compute these values at the end of the simulator analysing the logs or you can try to implement a monitor process in the simulation with your model.

**Comment by saad-eddine** [comment]
which example is provide the utilization of ressource on your Code

**Comment by saad-eddine** [comment]
Hi 
After  we try to run your examples to understand how it works , but i m facing a several eror 
Can you help please to fix it , you can give me your email to cantact you directly 
Thanks Isaac

<img width="443" alt="ERROR3" src="https://user-images.githubusercontent.com/12139490/81028853-9676b780-8e72-11ea-8fa7-49ab48d30f2b.PNG">
<img width="370" alt="ERROR4" src="https://user-images.githubusercontent.com/12139490/81028856-9971a800-8e72-11ea-866c-062ebf120358.PNG">
<img width="367" alt="ERROR5" src="https://user-images.githubusercontent.com/12139490/81028858-9b3b6b80-8e72-11ea-9c2a-147b56e0d72d.PNG">
<img width="364" alt="ERROR6" src="https://user-images.githubusercontent.com/12139490/81028863-9e365c00-8e72-11ea-82dc-b8396bc1a935.PNG">
<img width="365" alt="ERROR7" src="https://user-images.githubusercontent.com/12139490/81028867-9f678900-8e72-11ea-8bfa-e696ddb0e3e4.PNG">
<img width="366" alt="ERROR8" src="https://user-images.githubusercontent.com/12139490/81028888-a8f0f100-8e72-11ea-9f1d-a032fe09c7df.PNG">






![Uploading ERROR2.PNG…](

<img width="543" alt="ERROR1" src="https://user-images.githubusercontent.com/12139490/81028844-8f4fa980-8e72-11ea-9fa9-fa4ddc4688ef.PNG">

<img width="366" alt="ERROR" src="https://user-images.githubusercontent.com/12139490/81028835-88289b80-8e72-11ea-816d-88471075879c.PNG">

**Comment by wisaaco** [comment]
Hello,

You should follow the installation guide in the slides: https://www.slideshare.net/wisaaco/yet-another-fog-simulator-yafs-user-guide

- In the first case, you need to install the Scikit library (look at the slides).
- The CSV files (IOError) are not in the repo due to their size. YAFS execution is set by two steps the simulation and after that, you obtain the whole trace in the csv files. The analysis of the CSV depends on your study. So, you have to program your python script to obtain your measures. Other option more complex is that you can do the analysis along with the simulation. Please, see the documentation.
- The other two cases, I recommend you that install YAFS using the guide. YAFS pip version is very old.
