### ISSUE TITLE
Assigning distance between sensor and nodes

### ISSUE THREAD

**Issue by Sherlocked556** [acsicuib/YAFS#61]
Hi @wisaaco , I am trying to implement a network wherein I have fog nodes as well as cloud servers. I want to define this so that if the distance between the sensor and fog nodes is x, the distance between sensor and cloud should be 10 times x.  Can you please guide me on how I can implement this?

**Comment by wisaaco** [comment]
Hello @Sherlocked556

There are different ways, but it depends on the scale and dynamicity of your study.
On a small scale, you can do it manually. Use the JSON file (topology.json) to define the nodes and links, and use the file (allocDefinition.json) to define the application placement on those nodes where the condition is met. 
In a large scale infrastructure, you can create a script that given a topology (a graph) calculates the handover distance between nodes: https://networkx.org/documentation/stable/reference/algorithms/shortest_paths.html This script will search for those nodes where the condition you programmed is met.
