### ISSUE TITLE
Please update dependencies

### ISSUE THREAD

**Issue by ghost** [acsicuib/YAFS#63]
Hey
I tried to install YAFS with suggested PIP dependencies and it failed.
So
I updated dependencies list like that:
```
cython==0.29.30
decorator==4.4.2
networkx==2.5
numpy==1.22.4
simpy==4.0.1
pandas==1.4.2
```

And installed with this command:
```
python3.10 -m pip install -r requirements.txt

```
I`m not sure if will be any issues like that in futute, but keep in mind

See yaaaaa

**Comment by wisaaco** [comment]
Nice, annotated, 3.10 is far a future for all yafs' ecosystem ;)

**Comment by subwayi** [comment]
Hi @wisaaco,
I processed the YAFS3 within python3.6.
I followed the readme to install setup.py / requirements.
Ｍost of YAFS examples worked.

To get multiple viewpoints of fog computing,I would like to  run the other examples 
(like 'RuleBasedDistributeModel'/'PartitionILPPlacement'/'FogCentrality'/'FogTorchPI-Integration'/'MCDA')
,there would be some error like  [ModuleNotFoundError: No module named 'yafs.utils'].
In fact, the utils did not include in yafs folder of YAFS3.
I had tried to hide the yafs.utils related code, but it appeared the other errors.
Could you advise how to get rid of the errors?

Thank you.

Best,
Subwayi

**Comment by ghost** [comment]
@subwayi

I recommend you build YAFS-package with required depencies and install it with pip. It should work

**Comment by wisaaco** [comment]
Dear all,

I have not been able to spend more time on the yafs core project and it is a pity that the old examples from version 2.7 are not working with the current configuration. I will try in the next few days to update the whole structure of the project and include comments/improvements from other colleagues.  

Regards,
Isaac
