### ISSUE TITLE
Missing setup.py

### ISSUE THREAD

**Issue by adysonmaia** [acsicuib/YAFS#65]
The setup.py file was deleted in commit [e79e89b3bba4c84ca2f75cbc31742a0295de62e2](https://github.com/acsicuib/YAFS/commit/e79e89b3bba4c84ca2f75cbc31742a0295de62e2) 

This causes an error when setting up `YAFS` as a dependency module and installing it by pip:
`python -m pip install git+https://github.com/acsicuib/YAFS.git@YAFS3` 

and then the following error is returned:
`ERROR: File "setup.py" not found for legacy project git+https://github.com/acsicuib/YAFS.git@YAFS3`

**Comment by wisaaco** [comment]
Fixed! Thanks.
