### ISSUE TITLE
Propagation Rate Misnomer

### ISSUE THREAD

**Issue by jamesn1197** [acsicuib/YAFS#7]
Throughout the code, "propagation rate" is used to describe the base latency of a link, and it is noted that this is the case in topology.py L19. However, sometimes this is referred to as a rate (which is a reasonable mistranslation), and speed (inconsistent, given propagation speed would be orthogonal to bandwidth so the volume flow would have to be based on the product of these two).

Basically:
In the docs, it seems to me that 
Latency=Message.Size/(BW + PR)
should be:
Latency=(Message.Size/BW) + PR
based on the calculation made in L260-262 of core.py, and the comment in topology.py L19. Of course the parentheses are not necessary, but they make it clear that PR is not included in the fraction.

Thanks

**Comment by wisaaco** [comment]
Hi James,

Thank you for your comments and sorry for some Spanish literal mistranslations and some Spanish comments in the code. 

You are right, the formula of the latency in the docs has a mistake.

As we can see in the code (core.py) is computed using this structure: Latency=(Message.Size/BW) + PR
```
transmit = size_bits / (self.topology.get_edge(link)[Topology.LINK_BW] * 1000000.0)  # MBITS!
propagation = self.topology.get_edge(link)[Topology.LINK_PR]
latency_msg_link = transmit + propagation
```
I've updated the doc 

Best,
Isaac
