### ISSUE TITLE
Bug in tutorials/04_userMovement

### ISSUE THREAD

**Issue by felipedummer** [acsicuib/YAFS#76]
<img width="1300" alt="Screenshot 2024-08-21 at 20 32 24" src="https://github.com/user-attachments/assets/87dad8d9-57e8-456d-b958-8e935ac5d65b">

Is this logic correct?

`alloc_DES` contains information about the process (users in this custom monitor)running in each node. In this debugging, the process number 9 is running in node 23.

When the logic of moving a user from node X to node Y is triggered, it creates a new process with the number of the previous node and assigns a value of the new node to it.

The correct value should be **9 = 31** instead of **23 = 31**

![image](https://github.com/user-attachments/assets/7345fcd6-333e-429a-8d3c-b966af74381a)

**Comment by wisaaco** [comment]
Hi, 
You are right. Line 70 should be: 
```
sim.alloc_DES[userDES] = newNode
```

Thank you. 
Isaac
