### ISSUE TITLE
Missing files 

### ISSUE THREAD

**Issue by Raghad1997** [acsicuib/YAFS#8]
Hello, I found that your simulator very useful so I work on it for my graduation project. But I really face a problem that There are files missing when I run the simulation “. That read a network definition from Json file “. As shown in the picture :/  

![FFF9AFB6-D14C-475A-8103-48BCA8C02D44](https://user-images.githubusercontent.com/49207043/57111241-ef81ac00-6d43-11e9-8f41-bb88ddd953e3.jpeg)

**Comment by wisaaco** [comment]
Hi,
These files are generated from another tool to define a specific scenario.  This example is a complex example, it is not ideal to understand the basics of the simulator. In any case, I uploaded to the git a compressed file with all the experiment data: https://github.com/acsicuib/YAFS/blob/master/src/examples/MapReduceModel/files_exp.tar.gz

Please, update the path in the main.py and check the number of experiments (files and nodes) in the loops.

**Comment by wisaaco** [comment]
Hello,  
I forgot to mention that this implementation corresponds to this paper:

"Migration-Aware Genetic Optimization for MapReduce Scheduling and Replica Placement in Hadoop"  Journal of Grid Computing  [https://doi.org/10.1007/s10723-018-9432-8](https://doi.org/10.1007/s10723-018-9432-8)
Best,
Isaac

**Comment by Raghad1997** [comment]
Thank you very much ^_^
